networks:
  everbit-network:
    driver: bridge

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST=https://everbit.kr
    depends_on:
      - server
    networks:
      - everbit-network

  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./server/src/main/resources:/app/config
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks: 
      - everbit-network