networks:
  everbit-network:
    driver: bridge

services:
  client:
    build:
      context: ./client
    container_name: client
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_HOST=https://everbit.kr/api
      - NEXT_PUBLIC_SECURE_API_HOST=https://everbit.kr/api
      - TZ=Asia/Seoul
    depends_on:
      - server
    networks:
      - everbit-network

  server:
    build:
      context: ./server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks: 
      - everbit-network
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - everbit-network