-- everbit v2 MVP schema (PostgreSQL)
-- Source of truth: docs/architecture/data-model.md
-- NOTE: This file is an executable DDL draft. Adjust ON DELETE policy and indexes as needed,
--       but do not remove unique constraints that enforce idempotency.

-- Optional: UUID generator (gen_random_uuid)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------------------
-- 0) Helper domains / conventions (optional)
-- -----------------------------------------------------------------------------
-- ULID is generated by the application; stored as fixed-length char(26).
-- We do not enforce regex to avoid casing issues; char(26) already enforces length.

-- -----------------------------------------------------------------------------
-- 1) Core tables
-- -----------------------------------------------------------------------------

-- 1.1 app_user (avoid reserved word "user")
CREATE TABLE IF NOT EXISTS app_user (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id   char(26) NOT NULL UNIQUE,
  kakao_id    varchar(64) NOT NULL UNIQUE,
  email       varchar(255),
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- 1.2 upbit_key (shared PK: owner_id)
CREATE TABLE IF NOT EXISTS upbit_key (
  owner_id        bigint PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
  access_key_enc  bytea  NOT NULL,
  secret_key_enc  bytea  NOT NULL,
  key_version     int    NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  rotated_at      timestamptz
);

-- 1.3 strategy_config (composite PK)
CREATE TABLE IF NOT EXISTS strategy_config (
  owner_id       bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  strategy_key   varchar(64) NOT NULL,
  config_version int NOT NULL DEFAULT 1,
  config_json    jsonb NOT NULL,
  updated_at     timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, strategy_key)
);

-- 1.4 market_config (composite PK)
CREATE TABLE IF NOT EXISTS market_config (
  owner_id    bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  market      varchar(32) NOT NULL,
  enabled     boolean NOT NULL DEFAULT true,
  priority    int NOT NULL DEFAULT 0,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, market)
);

-- 1.5 kill_switch (shared PK)
CREATE TABLE IF NOT EXISTS kill_switch (
  owner_id           bigint PRIMARY KEY REFERENCES app_user(id) ON DELETE CASCADE,
  account_enabled    boolean NOT NULL DEFAULT true,
  enabled_strategies jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- -----------------------------------------------------------------------------
-- 2) Trading pipeline tables
-- -----------------------------------------------------------------------------

-- 2.1 signal (idempotency start point)
CREATE TABLE IF NOT EXISTS signal (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id         char(26) NOT NULL UNIQUE,
  owner_id          bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  strategy_key      varchar(64) NOT NULL,
  market            varchar(32) NOT NULL,
  timeframe         varchar(16) NOT NULL,
  candle_close_time timestamptz NOT NULL,
  side              varchar(8) NOT NULL CHECK (side IN ('BUY','SELL')),
  strength          numeric(18,8) NOT NULL DEFAULT 0,
  reason_code       varchar(64),
  signal_json       jsonb,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_signal_idempotency UNIQUE (owner_id, strategy_key, market, timeframe, candle_close_time, side)
);

CREATE INDEX IF NOT EXISTS ix_signal_owner_created_at ON signal(owner_id, created_at);

-- 2.2 order_intent
CREATE TABLE IF NOT EXISTS order_intent (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id        char(26) NOT NULL UNIQUE,
  owner_id         bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  signal_id        bigint NOT NULL REFERENCES signal(id) ON DELETE RESTRICT,
  intent_type      varchar(32) NOT NULL CHECK (intent_type IN ('ENTRY','EXIT_STOPLOSS','EXIT_TP','EXIT_TRAIL','EXIT_TIME')),
  status           varchar(16) NOT NULL CHECK (status IN ('CREATED','CANCELED','COMPLETED')),
  market           varchar(32) NOT NULL,
  side             varchar(8)  NOT NULL CHECK (side IN ('BUY','SELL')),
  requested_krw    numeric(38,18),
  requested_volume numeric(38,18),
  reason_code      varchar(64),
  created_at       timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_order_intent_per_type UNIQUE (signal_id, intent_type)
);

CREATE INDEX IF NOT EXISTS ix_order_intent_owner_created_at ON order_intent(owner_id, created_at);

-- 2.3 order_attempt
CREATE TABLE IF NOT EXISTS order_attempt (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id       char(26) NOT NULL UNIQUE,
  owner_id        bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  order_intent_id bigint NOT NULL REFERENCES order_intent(id) ON DELETE CASCADE,
  attempt_no      int NOT NULL CHECK (attempt_no >= 1),
  identifier      varchar(64) NOT NULL,
  upbit_uuid      uuid,
  status          varchar(16) NOT NULL CHECK (status IN ('PREPARED','SENT','ACKED','REJECTED','THROTTLED','UNKNOWN','SUSPENDED')),
  error_code      varchar(64),
  error_message   text,
  next_retry_at   timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_order_attempt_no UNIQUE (order_intent_id, attempt_no),
  CONSTRAINT ux_order_attempt_identifier UNIQUE (identifier)
);

CREATE INDEX IF NOT EXISTS ix_order_attempt_owner_created_at ON order_attempt(owner_id, created_at);
CREATE INDEX IF NOT EXISTS ix_order_attempt_status_next_retry ON order_attempt(status, next_retry_at);

-- 2.4 upbit_order (external order snapshot)
CREATE TABLE IF NOT EXISTS upbit_order (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id        bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  upbit_uuid      uuid NOT NULL UNIQUE,
  identifier      varchar(64),
  market          varchar(32) NOT NULL,
  side            varchar(8)  NOT NULL, -- Upbit raw: bid/ask
  ord_type        varchar(16) NOT NULL, -- Upbit raw: limit/market/price/best
  state           varchar(16) NOT NULL, -- Upbit raw: wait/done/cancel/...
  price           numeric(38,18),
  volume          numeric(38,18),
  executed_volume numeric(38,18) NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ix_upbit_order_owner_created_at ON upbit_order(owner_id, created_at);

-- 2.5 fill (trade executions; idempotent by trade_uuid)
CREATE TABLE IF NOT EXISTS fill (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id   bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  upbit_uuid uuid NOT NULL,
  trade_uuid uuid NOT NULL UNIQUE,
  trade_time timestamptz NOT NULL,
  price      numeric(38,18) NOT NULL,
  volume     numeric(38,18) NOT NULL,
  fee        numeric(38,18),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT fk_fill_upbit_uuid FOREIGN KEY (upbit_uuid) REFERENCES upbit_order(upbit_uuid) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_fill_upbit_uuid_trade_time ON fill(upbit_uuid, trade_time);

-- 2.6 position (composite PK)
CREATE TABLE IF NOT EXISTS position (
  owner_id   bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  market     varchar(32) NOT NULL,
  quantity   numeric(38,18) NOT NULL DEFAULT 0,
  avg_price  numeric(38,18) NOT NULL DEFAULT 0,
  status     varchar(16) NOT NULL CHECK (status IN ('FLAT','OPEN','SUSPENDED')),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (owner_id, market)
);

-- 2.7 pnl_snapshot
CREATE TABLE IF NOT EXISTS pnl_snapshot (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id       bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  market         varchar(32) NOT NULL,
  realized_pnl   numeric(38,18) NOT NULL DEFAULT 0,
  unrealized_pnl numeric(38,18) NOT NULL DEFAULT 0,
  equity         numeric(38,18) NOT NULL DEFAULT 0,
  captured_at    timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_pnl_snapshot_owner_captured_at ON pnl_snapshot(owner_id, captured_at);

-- -----------------------------------------------------------------------------
-- 3) Outbox / Queue
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS outbox_event (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id            uuid NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  stream              varchar(128) NOT NULL,
  event_type          varchar(128) NOT NULL,
  aggregate_type      varchar(64)  NOT NULL,
  aggregate_id        bigint,
  payload_json        jsonb NOT NULL,
  status              varchar(16) NOT NULL CHECK (status IN ('PENDING','PROCESSING','DONE','DEAD')),
  attempt_count       int NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts        int NOT NULL DEFAULT 10 CHECK (max_attempts >= 1),
  next_retry_at       timestamptz NOT NULL DEFAULT now(),
  last_attempt_at     timestamptz,
  locked_by           varchar(128),
  locked_until        timestamptz,
  last_error_code     varchar(64),
  last_error_message  text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  processed_at        timestamptz
);

-- Claim query support
CREATE INDEX IF NOT EXISTS ix_outbox_stream_status_next_retry ON outbox_event(stream, status, next_retry_at);
CREATE INDEX IF NOT EXISTS ix_outbox_status_next_retry ON outbox_event(status, next_retry_at);
CREATE INDEX IF NOT EXISTS ix_outbox_created_at ON outbox_event(created_at);
CREATE INDEX IF NOT EXISTS ix_outbox_status_locked_until ON outbox_event(status, locked_until);

-- -----------------------------------------------------------------------------
-- 4) Push notifications
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS push_subscription (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id   bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  endpoint   text NOT NULL,
  p256dh     text NOT NULL,
  auth       text NOT NULL,
  user_agent text,
  enabled    boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_push_subscription UNIQUE (owner_id, endpoint)
);

CREATE TABLE IF NOT EXISTS notification_log (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id     bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  event_id     uuid NOT NULL,
  type         varchar(64) NOT NULL,
  payload_json jsonb NOT NULL,
  delivered_at timestamptz,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ux_notification_dedupe UNIQUE (owner_id, event_id)
);

-- -----------------------------------------------------------------------------
-- 5) Backtest
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS backtest_job (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  public_id    char(26) NOT NULL UNIQUE,
  owner_id     bigint NOT NULL REFERENCES app_user(id) ON DELETE CASCADE,
  status       varchar(16) NOT NULL CHECK (status IN ('QUEUED','RUNNING','DONE','FAILED')),
  request_json jsonb NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS backtest_result (
  job_id            bigint PRIMARY KEY REFERENCES backtest_job(id) ON DELETE CASCADE,
  metrics_json      jsonb NOT NULL,
  equity_curve_json jsonb,
  created_at        timestamptz NOT NULL DEFAULT now()
);
